tap "caskroom/drivers"
brew "heroku"
brew "hub"
cask "dropbox"
cask "google-chrome"
cask "sublime-text"
cask "logitech-options"
cask "litecoin"
cask "bittorrent"
mas "Microsoft Remote Desktop", id: 715768417
